spring:
  flyway:
    locations: classpath:db/migration/common
jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "http://localhost:8180"
          jwk-set-uri: "http://localhost:8180/.well-known/jwks.json"
cc-printing-service:
  allowed-origin: "http://localhost:4201"
  monitor:
    prometheus:
      user: "prometheus"
      password: "{noop}secret"
  service:
    sleepLogInterval: 1
  print-queue:
    schedule: "0 */5 * * * *"
    cleanup-schedule: "0 */5 * * * *"
    cleanup-until-number-of-days: 2
  temp-folder: "./temp/certificates"
  zip-size: 1000
  internal:
    maintenance:
      user: "user1"
      password: "{noop}user1Pass"

## Uncomment the following to increase logging; then issue
## `mvn compile` to copy this configuration under target/
# server:
#   tomcat:
#     basedir: /tmp
#     accesslog:
#       enabled: true
#       directory: /dev
#       prefix: stdout
#       buffered: false
#       suffix:
#       file-date-format:
#
# logging:
#   level:
#     org.apache.tomcat: DEBUG
#     org.apache.catalina: DEBUG
#     org:
#       apache:
#         tomcat: DEBUG
#         catalina: DEBUG


bbl:
  sftp:
    host: localhost
    port: 2222
    user: foo
    password: pass
    known_hosts: W2xvY2FsaG9zdF06MjIyMiBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUNBUUM0bUxlcjR4Y3Z0czB1LzRuUG12akJMM2lDWngwbGlLNEUrR3NPRkovMEl4VDhRSTFnZUp6eXgvcUhCNktnUDVxN085NkR4bThTd2szaGVSNm5XNGhteUhuOGcvUUJxTDRNdXRQUzJhUCtET00wdmZHTkJnNUF6eFFqL2hsVko5cWgwbVp1VTdKV3pOMUUrRzN2c2FqNjBaMHYrdXppTDVOTjBSLy9hVGFhUDZCYjdUZUNXUlZ5eGR3SGJzcXBaVk1mNlIySmxtY1k0TVAxeFhBYlZlZFc0NGlzMFlWUFh3cmNhWHNYM05jU3BVdEgwY2o0MDdIVkg3ajBoY1cxSm9ET3Fub1hBOW5jZUhFYmYyUzIzRk1rZWZEcFRJVmNjd2NxckNuVzNsRzcrZkRPZ3BpZGNHRHIwTGY4eDlKRWhrK2xaM1o2Ykl5dGhBT0xQVWNVcDhCMVhMTGx1QnZycGg4b1NiaHVuN1BFSlVkOHlWSVovelBlSzhDR3VKR1VhMC90SDA2L0xxc0JpYytxVDVGQ2QyQ09ScXdGQ2swbEZqLzZVYnRMQ2VpelhJRkY2QlJsa29sMU5QSFJJUXc5ZlQvY0tNK2ZlUEVmTW82eHFOVEdEYUZGaWU5YlJRdGY2b3JJRnV5ZjBRSlEwTkh3eFBGRHBVdW96RVR5bXNqb3F6cngvZ1ZjK3lFbTJBQi9sY2E1R1pubDZlUFNRVHlkWEIwU0g4MjFZSDl1MGVPZk8vTWRKUit4TCt6dnRyWVl5VVV2UEwyeUhSRE9WdFBBWkNCYmR1TGRhR3dHakhqSHJDV2hqVUFPYXpDVHM2OGE4NXdBVy9GRWNyVmJHc0JCZmlIUnJWU3I5SXd0am1KcTlwanU1Y0JkaWN1VFhWWDIxU1JXWkp5TGN1YVVNdz09Cltsb2NhbGhvc3RdOjIyMjIgc3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU15bmdKRDl6SU5PNitkYjhZMmlzM0NJZ0k0Q3Irc0lSSGJWZkNZSjRTbXgK
